package testNGpackage;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ExtensioncodeTest {
  private WebDriver driver;
  private Map<String, Object> vars;  
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void extensioncode() {
    driver.get("https://www.google.com/search?q=books&sca_esv=566970484&sxsrf=AM9HkKmIh72UB8MDFwa4_Lm_M0mto9quaA%3A1695226033913&source=hp&ei=sRgLZa-ANYuhhwOtvoYQ&iflsig=AO6bgOgAAAAAZQsmwVVcT-uL9780u6vYZ8q1r2_fZ8H2&ved=0ahUKEwjvnMCMybmBAxWL0GEKHS2fAQIQ4dUDCAk&uact=5&oq=books&gs_lp=Egdnd3Mtd2l6IgVib29rczIEECMYJzILEAAYigUYsQMYkQIyChAAGIoFGLEDGEMyDRAAGIoFGLEDGIMBGEMyChAAGIoFGLEDGEMyDRAAGIoFGLEDGIMBGEMyCxAuGIAEGLEDGIMBMggQABiABBixAzIHEAAYigUYQzIFEAAYgARIhhlQAFj5EXAAeACQAQGYAd0FoAHaEqoBCTItMS4yLjYtMrgBA8gBAPgBAcICBxAjGIoFGCfCAggQABiKBRiRAsICCxAAGIoFGLEDGIMBwgIFEC4YgATCAgQQABgDwgIOEAAYigUYsQMYgwEYkQLCAg4QABiKBRixAxjJAxiRAsICCBAAGIAEGJIDwgIREC4YgAQYsQMYgwEYxwEY0QPCAgsQABiABBixAxiDAcICDhAAGIAEGLEDGIMBGJIDwgIHEC4YigUYQw&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.id("APjFqb")).click();
    driver.findElement(By.cssSelector(".WggQGd > span")).click();
  }
}
